#pragma once

// Auto-generated from 00021.mp3
// DO NOT EDIT - Generated by tools/audio_to_pcm_header.py

#include <cstdint>
#include <cstddef>

namespace Exterminate {
namespace Audio {

// PCM audio data for 00021.mp3
// Format: 44100Hz, 1 channel(s), 16-bit PCM
// Duration: 5252ms (231,647 samples)
extern const int16_t AUDIO_00021_DATA[];
extern const size_t AUDIO_00021_SAMPLE_COUNT;
extern const size_t AUDIO_00021_BYTE_SIZE;
extern const uint32_t AUDIO_00021_SAMPLE_RATE;
extern const uint8_t AUDIO_00021_CHANNELS;
extern const uint8_t AUDIO_00021_BIT_DEPTH;

} // namespace Audio
} // namespace Exterminate
