#pragma once

// Auto-generated PCM audio index
// DO NOT EDIT - Generated by tools/audio_to_pcm_header.py

#include <cstdint>
#include <cstddef>
#include <cstring>

#include "00001.h"

namespace Exterminate {
namespace Audio {

// Audio format constants
constexpr uint32_t AUDIO_SAMPLE_RATE = 44100;
constexpr uint8_t AUDIO_CHANNELS = 1;
constexpr uint8_t AUDIO_BIT_DEPTH = 16;

// PCM audio file registry
struct AudioFile {
    const char* name;
    const int16_t* data;
    size_t sample_count;
    size_t byte_size;
    uint32_t sample_rate;
    uint8_t channels;
    uint8_t bit_depth;
};

// Available audio files
extern const AudioFile AUDIO_FILES[];
extern const size_t AUDIO_FILE_COUNT;

// Audio file indices for easy access
enum class AudioIndex : size_t {
    AUDIO_00001 = 0,
    COUNT = 1
};

// Helper functions
const AudioFile* getAudioFile(AudioIndex index);
const AudioFile* getAudioFile(const char* name);

} // namespace Audio
} // namespace Exterminate
