// Audio index implementations for Exterminate project
// This file contains the actual definitions for audio file registry
// 
// Auto-generated by tools/audio_to_pcm_header.py - DO NOT EDIT MANUALLY

#include "../include/audio/audio_index.h"

namespace Exterminate {
namespace Audio {

const AudioFile AUDIO_FILES[] = {
    {"00001.mp3", AUDIO_00001_DATA, AUDIO_00001_SAMPLE_COUNT, AUDIO_00001_BYTE_SIZE,
     AUDIO_00001_SAMPLE_RATE, AUDIO_00001_CHANNELS, AUDIO_00001_BIT_DEPTH},
};

const size_t AUDIO_FILE_COUNT = 1;

const AudioFile* getAudioFile(AudioIndex index) {
    if (static_cast<size_t>(index) >= AUDIO_FILE_COUNT) {
        return nullptr;
    }
    return &AUDIO_FILES[static_cast<size_t>(index)];
}

const AudioFile* getAudioFile(const char* name) {
    for (size_t i = 0; i < AUDIO_FILE_COUNT; ++i) {
        if (strcmp(AUDIO_FILES[i].name, name) == 0) {
            return &AUDIO_FILES[i];
        }
    }
    return nullptr;
}

} // namespace Audio
} // namespace Exterminate
